service: web-page
provider:
  name: aws
  runtime: python3.8

package:
  include:
    - requirements.txt


functions:
  app:
    handler: app.app
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
