name: Deploy the code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        uses: aws-actions/setup-aws-cli@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install Serverless Framework
        run: npm i -g serverless
      - name: Deploy to Lambda
        run: serverless deploy
